package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AccessLevel generated by hbm2java
 */
public class AccessLevel  implements java.io.Serializable {


     private Integer id;
     private int level;
     private String descriptin;
     private Set<CustomAccessLevel> customAccessLevels = new HashSet<CustomAccessLevel>(0);
     private Set<User> users = new HashSet<User>(0);

    public AccessLevel() {
    }

	
    public AccessLevel(int level) {
        this.level = level;
    }
    public AccessLevel(int level, String descriptin, Set<CustomAccessLevel> customAccessLevels, Set<User> users) {
       this.level = level;
       this.descriptin = descriptin;
       this.customAccessLevels = customAccessLevels;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public String getDescriptin() {
        return this.descriptin;
    }
    
    public void setDescriptin(String descriptin) {
        this.descriptin = descriptin;
    }
    public Set<CustomAccessLevel> getCustomAccessLevels() {
        return this.customAccessLevels;
    }
    
    public void setCustomAccessLevels(Set<CustomAccessLevel> customAccessLevels) {
        this.customAccessLevels = customAccessLevels;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


