package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * AdLogin generated by hbm2java
 */
public class AdLogin  implements java.io.Serializable {


     private Integer idAdLogin;
     private String adLoginName;
     private String userName;
     private String empNo;
     private String department;

    public AdLogin() {
    }

    public AdLogin(String adLoginName, String userName, String empNo, String department) {
       this.adLoginName = adLoginName;
       this.userName = userName;
       this.empNo = empNo;
       this.department = department;
    }
   
    public Integer getIdAdLogin() {
        return this.idAdLogin;
    }
    
    public void setIdAdLogin(Integer idAdLogin) {
        this.idAdLogin = idAdLogin;
    }
    public String getAdLoginName() {
        return this.adLoginName;
    }
    
    public void setAdLoginName(String adLoginName) {
        this.adLoginName = adLoginName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


