package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ArticleCat generated by hbm2java
 */
public class ArticleCat  implements java.io.Serializable {


     private Integer idCat;
     private String articleDetails;
     private Set<Article> articles = new HashSet<Article>(0);

    public ArticleCat() {
    }

	
    public ArticleCat(String articleDetails) {
        this.articleDetails = articleDetails;
    }
    public ArticleCat(String articleDetails, Set<Article> articles) {
       this.articleDetails = articleDetails;
       this.articles = articles;
    }
   
    public Integer getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(Integer idCat) {
        this.idCat = idCat;
    }
    public String getArticleDetails() {
        return this.articleDetails;
    }
    
    public void setArticleDetails(String articleDetails) {
        this.articleDetails = articleDetails;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }




}


