package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idArticle;
     private ArticleCat articleCat;
     private String articleName;
     private String articleDetail;
     private Date createdDate;
     private boolean isActive;
     private Set<ArticleBacklog> articleBacklogs = new HashSet<ArticleBacklog>(0);
     private Set<ExistingEmpList> existingEmpLists = new HashSet<ExistingEmpList>(0);
     private Set<NarrowvationArticle> narrowvationArticles = new HashSet<NarrowvationArticle>(0);

    public Article() {
    }

	
    public Article(ArticleCat articleCat, String articleName, String articleDetail, Date createdDate, boolean isActive) {
        this.articleCat = articleCat;
        this.articleName = articleName;
        this.articleDetail = articleDetail;
        this.createdDate = createdDate;
        this.isActive = isActive;
    }
    public Article(ArticleCat articleCat, String articleName, String articleDetail, Date createdDate, boolean isActive, Set<ArticleBacklog> articleBacklogs, Set<ExistingEmpList> existingEmpLists, Set<NarrowvationArticle> narrowvationArticles) {
       this.articleCat = articleCat;
       this.articleName = articleName;
       this.articleDetail = articleDetail;
       this.createdDate = createdDate;
       this.isActive = isActive;
       this.articleBacklogs = articleBacklogs;
       this.existingEmpLists = existingEmpLists;
       this.narrowvationArticles = narrowvationArticles;
    }
   
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }
    public ArticleCat getArticleCat() {
        return this.articleCat;
    }
    
    public void setArticleCat(ArticleCat articleCat) {
        this.articleCat = articleCat;
    }
    public String getArticleName() {
        return this.articleName;
    }
    
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }
    public String getArticleDetail() {
        return this.articleDetail;
    }
    
    public void setArticleDetail(String articleDetail) {
        this.articleDetail = articleDetail;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set<ArticleBacklog> getArticleBacklogs() {
        return this.articleBacklogs;
    }
    
    public void setArticleBacklogs(Set<ArticleBacklog> articleBacklogs) {
        this.articleBacklogs = articleBacklogs;
    }
    public Set<ExistingEmpList> getExistingEmpLists() {
        return this.existingEmpLists;
    }
    
    public void setExistingEmpLists(Set<ExistingEmpList> existingEmpLists) {
        this.existingEmpLists = existingEmpLists;
    }
    public Set<NarrowvationArticle> getNarrowvationArticles() {
        return this.narrowvationArticles;
    }
    
    public void setNarrowvationArticles(Set<NarrowvationArticle> narrowvationArticles) {
        this.narrowvationArticles = narrowvationArticles;
    }




}


