package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CandidatesBacklog generated by hbm2java
 */
public class CandidatesBacklog  implements java.io.Serializable {


     private Integer idCandidatesBacklog;
     private IntervieweeDetails intervieweeDetails;
     private User user;
     private String details;
     private Date upDateTime;

    public CandidatesBacklog() {
    }

    public CandidatesBacklog(IntervieweeDetails intervieweeDetails, User user, String details, Date upDateTime) {
       this.intervieweeDetails = intervieweeDetails;
       this.user = user;
       this.details = details;
       this.upDateTime = upDateTime;
    }
   
    public Integer getIdCandidatesBacklog() {
        return this.idCandidatesBacklog;
    }
    
    public void setIdCandidatesBacklog(Integer idCandidatesBacklog) {
        this.idCandidatesBacklog = idCandidatesBacklog;
    }
    public IntervieweeDetails getIntervieweeDetails() {
        return this.intervieweeDetails;
    }
    
    public void setIntervieweeDetails(IntervieweeDetails intervieweeDetails) {
        this.intervieweeDetails = intervieweeDetails;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getUpDateTime() {
        return this.upDateTime;
    }
    
    public void setUpDateTime(Date upDateTime) {
        this.upDateTime = upDateTime;
    }




}


