package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * ConfidentiallRrf generated by hbm2java
 */
public class ConfidentiallRrf  implements java.io.Serializable {


     private Integer id;
     private ConfidentialType confidentialType;
     private Rrf rrf;

    public ConfidentiallRrf() {
    }

    public ConfidentiallRrf(ConfidentialType confidentialType, Rrf rrf) {
       this.confidentialType = confidentialType;
       this.rrf = rrf;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ConfidentialType getConfidentialType() {
        return this.confidentialType;
    }
    
    public void setConfidentialType(ConfidentialType confidentialType) {
        this.confidentialType = confidentialType;
    }
    public Rrf getRrf() {
        return this.rrf;
    }
    
    public void setRrf(Rrf rrf) {
        this.rrf = rrf;
    }




}


