package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ConfidentialType generated by hbm2java
 */
public class ConfidentialType  implements java.io.Serializable {


     private Integer idConfidentialType;
     private String details;
     private Set<ConfidentiallRrf> confidentiallRrfs = new HashSet<ConfidentiallRrf>(0);

    public ConfidentialType() {
    }

	
    public ConfidentialType(String details) {
        this.details = details;
    }
    public ConfidentialType(String details, Set<ConfidentiallRrf> confidentiallRrfs) {
       this.details = details;
       this.confidentiallRrfs = confidentiallRrfs;
    }
   
    public Integer getIdConfidentialType() {
        return this.idConfidentialType;
    }
    
    public void setIdConfidentialType(Integer idConfidentialType) {
        this.idConfidentialType = idConfidentialType;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set<ConfidentiallRrf> getConfidentiallRrfs() {
        return this.confidentiallRrfs;
    }
    
    public void setConfidentiallRrfs(Set<ConfidentiallRrf> confidentiallRrfs) {
        this.confidentiallRrfs = confidentiallRrfs;
    }




}


