package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomStatus generated by hbm2java
 */
public class CustomStatus  implements java.io.Serializable {


     private Integer idStates;
     private TypeOfStatus typeOfStatus;
     private String statesName;
     private Set<TerminatedEmployees> terminatedEmployeeses = new HashSet<TerminatedEmployees>(0);
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);

    public CustomStatus() {
    }

	
    public CustomStatus(TypeOfStatus typeOfStatus, String statesName) {
        this.typeOfStatus = typeOfStatus;
        this.statesName = statesName;
    }
    public CustomStatus(TypeOfStatus typeOfStatus, String statesName, Set<TerminatedEmployees> terminatedEmployeeses, Set<Rrf> rrfs) {
       this.typeOfStatus = typeOfStatus;
       this.statesName = statesName;
       this.terminatedEmployeeses = terminatedEmployeeses;
       this.rrfs = rrfs;
    }
   
    public Integer getIdStates() {
        return this.idStates;
    }
    
    public void setIdStates(Integer idStates) {
        this.idStates = idStates;
    }
    public TypeOfStatus getTypeOfStatus() {
        return this.typeOfStatus;
    }
    
    public void setTypeOfStatus(TypeOfStatus typeOfStatus) {
        this.typeOfStatus = typeOfStatus;
    }
    public String getStatesName() {
        return this.statesName;
    }
    
    public void setStatesName(String statesName) {
        this.statesName = statesName;
    }
    public Set<TerminatedEmployees> getTerminatedEmployeeses() {
        return this.terminatedEmployeeses;
    }
    
    public void setTerminatedEmployeeses(Set<TerminatedEmployees> terminatedEmployeeses) {
        this.terminatedEmployeeses = terminatedEmployeeses;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }




}


