package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmploymentBasis generated by hbm2java
 */
public class EmploymentBasis  implements java.io.Serializable {


     private Integer idEmpType;
     private String empTypeData;
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);

    public EmploymentBasis() {
    }

	
    public EmploymentBasis(String empTypeData) {
        this.empTypeData = empTypeData;
    }
    public EmploymentBasis(String empTypeData, Set<Rrf> rrfs) {
       this.empTypeData = empTypeData;
       this.rrfs = rrfs;
    }
   
    public Integer getIdEmpType() {
        return this.idEmpType;
    }
    
    public void setIdEmpType(Integer idEmpType) {
        this.idEmpType = idEmpType;
    }
    public String getEmpTypeData() {
        return this.empTypeData;
    }
    
    public void setEmpTypeData(String empTypeData) {
        this.empTypeData = empTypeData;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }




}


