package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * EmpNic generated by hbm2java
 */
public class EmpNic  implements java.io.Serializable {


     private Integer idNic;
     private String nicNumber;
     private String epfNumber;

    public EmpNic() {
    }

    public EmpNic(String nicNumber, String epfNumber) {
       this.nicNumber = nicNumber;
       this.epfNumber = epfNumber;
    }
   
    public Integer getIdNic() {
        return this.idNic;
    }
    
    public void setIdNic(Integer idNic) {
        this.idNic = idNic;
    }
    public String getNicNumber() {
        return this.nicNumber;
    }
    
    public void setNicNumber(String nicNumber) {
        this.nicNumber = nicNumber;
    }
    public String getEpfNumber() {
        return this.epfNumber;
    }
    
    public void setEpfNumber(String epfNumber) {
        this.epfNumber = epfNumber;
    }




}


