package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EvaluationDocument generated by hbm2java
 */
public class EvaluationDocument  implements java.io.Serializable {


     private Integer idEd;
     private Set<IntervieweeDetails> intervieweeDetailses = new HashSet<IntervieweeDetails>(0);

    public EvaluationDocument() {
    }

    public EvaluationDocument(Set<IntervieweeDetails> intervieweeDetailses) {
       this.intervieweeDetailses = intervieweeDetailses;
    }
   
    public Integer getIdEd() {
        return this.idEd;
    }
    
    public void setIdEd(Integer idEd) {
        this.idEd = idEd;
    }
    public Set<IntervieweeDetails> getIntervieweeDetailses() {
        return this.intervieweeDetailses;
    }
    
    public void setIntervieweeDetailses(Set<IntervieweeDetails> intervieweeDetailses) {
        this.intervieweeDetailses = intervieweeDetailses;
    }




}


