package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExistingEmpList generated by hbm2java
 */
public class ExistingEmpList  implements java.io.Serializable {


     private Integer idExistingEmpList;
     private String epf;
     private String existingEmpListcol;
     private String callingName;
     private String surname;
     private String designation;
     private String cadre;
     private String empCategoy;
     private Date confirmedDate;
     private Date joinedDate;
     private String allianzGroup;
     private String department;
     private Boolean gender;
     private String existingEmpListcol1;
     private Date dob;
     private String workStation;
     private Boolean isWorking;
     private String proPicPath;
     private Set<NarrowvationArticle> narrowvationArticles = new HashSet<NarrowvationArticle>(0);
     private Set<ReportingPersonRrf> reportingPersonRrfs = new HashSet<ReportingPersonRrf>(0);
     private Set<EmployeeBacklog> employeeBacklogs = new HashSet<EmployeeBacklog>(0);
     private Set<Rnd> rnds = new HashSet<Rnd>(0);
     private Set<TerminatedEmployees> terminatedEmployeeses = new HashSet<TerminatedEmployees>(0);
     private Set<Article> articles = new HashSet<Article>(0);

    public ExistingEmpList() {
    }

    public ExistingEmpList(String epf, String existingEmpListcol, String callingName, String surname, String designation, String cadre, String empCategoy, Date confirmedDate, Date joinedDate, String allianzGroup, String department, Boolean gender, String existingEmpListcol1, Date dob, String workStation, Boolean isWorking, String proPicPath, Set<NarrowvationArticle> narrowvationArticles, Set<ReportingPersonRrf> reportingPersonRrfs, Set<EmployeeBacklog> employeeBacklogs, Set<Rnd> rnds, Set<TerminatedEmployees> terminatedEmployeeses, Set<Article> articles) {
       this.epf = epf;
       this.existingEmpListcol = existingEmpListcol;
       this.callingName = callingName;
       this.surname = surname;
       this.designation = designation;
       this.cadre = cadre;
       this.empCategoy = empCategoy;
       this.confirmedDate = confirmedDate;
       this.joinedDate = joinedDate;
       this.allianzGroup = allianzGroup;
       this.department = department;
       this.gender = gender;
       this.existingEmpListcol1 = existingEmpListcol1;
       this.dob = dob;
       this.workStation = workStation;
       this.isWorking = isWorking;
       this.proPicPath = proPicPath;
       this.narrowvationArticles = narrowvationArticles;
       this.reportingPersonRrfs = reportingPersonRrfs;
       this.employeeBacklogs = employeeBacklogs;
       this.rnds = rnds;
       this.terminatedEmployeeses = terminatedEmployeeses;
       this.articles = articles;
    }
   
    public Integer getIdExistingEmpList() {
        return this.idExistingEmpList;
    }
    
    public void setIdExistingEmpList(Integer idExistingEmpList) {
        this.idExistingEmpList = idExistingEmpList;
    }
    public String getEpf() {
        return this.epf;
    }
    
    public void setEpf(String epf) {
        this.epf = epf;
    }
    public String getExistingEmpListcol() {
        return this.existingEmpListcol;
    }
    
    public void setExistingEmpListcol(String existingEmpListcol) {
        this.existingEmpListcol = existingEmpListcol;
    }
    public String getCallingName() {
        return this.callingName;
    }
    
    public void setCallingName(String callingName) {
        this.callingName = callingName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getCadre() {
        return this.cadre;
    }
    
    public void setCadre(String cadre) {
        this.cadre = cadre;
    }
    public String getEmpCategoy() {
        return this.empCategoy;
    }
    
    public void setEmpCategoy(String empCategoy) {
        this.empCategoy = empCategoy;
    }
    public Date getConfirmedDate() {
        return this.confirmedDate;
    }
    
    public void setConfirmedDate(Date confirmedDate) {
        this.confirmedDate = confirmedDate;
    }
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }
    public String getAllianzGroup() {
        return this.allianzGroup;
    }
    
    public void setAllianzGroup(String allianzGroup) {
        this.allianzGroup = allianzGroup;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public String getExistingEmpListcol1() {
        return this.existingEmpListcol1;
    }
    
    public void setExistingEmpListcol1(String existingEmpListcol1) {
        this.existingEmpListcol1 = existingEmpListcol1;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getWorkStation() {
        return this.workStation;
    }
    
    public void setWorkStation(String workStation) {
        this.workStation = workStation;
    }
    public Boolean getIsWorking() {
        return this.isWorking;
    }
    
    public void setIsWorking(Boolean isWorking) {
        this.isWorking = isWorking;
    }
    public String getProPicPath() {
        return this.proPicPath;
    }
    
    public void setProPicPath(String proPicPath) {
        this.proPicPath = proPicPath;
    }
    public Set<NarrowvationArticle> getNarrowvationArticles() {
        return this.narrowvationArticles;
    }
    
    public void setNarrowvationArticles(Set<NarrowvationArticle> narrowvationArticles) {
        this.narrowvationArticles = narrowvationArticles;
    }
    public Set<ReportingPersonRrf> getReportingPersonRrfs() {
        return this.reportingPersonRrfs;
    }
    
    public void setReportingPersonRrfs(Set<ReportingPersonRrf> reportingPersonRrfs) {
        this.reportingPersonRrfs = reportingPersonRrfs;
    }
    public Set<EmployeeBacklog> getEmployeeBacklogs() {
        return this.employeeBacklogs;
    }
    
    public void setEmployeeBacklogs(Set<EmployeeBacklog> employeeBacklogs) {
        this.employeeBacklogs = employeeBacklogs;
    }
    public Set<Rnd> getRnds() {
        return this.rnds;
    }
    
    public void setRnds(Set<Rnd> rnds) {
        this.rnds = rnds;
    }
    public Set<TerminatedEmployees> getTerminatedEmployeeses() {
        return this.terminatedEmployeeses;
    }
    
    public void setTerminatedEmployeeses(Set<TerminatedEmployees> terminatedEmployeeses) {
        this.terminatedEmployeeses = terminatedEmployeeses;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }




}


