package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * GeneralInformation generated by hbm2java
 */
public class GeneralInformation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer numberOfEmp;
     private String taxId;
     private String registrationNo;
     private String phone;
     private String mail;
     private String fax;
     private String address;
     private String city;
     private String zipcode;
     private String country;
     private String note;

    public GeneralInformation() {
    }

	
    public GeneralInformation(String name) {
        this.name = name;
    }
    public GeneralInformation(String name, Integer numberOfEmp, String taxId, String registrationNo, String phone, String mail, String fax, String address, String city, String zipcode, String country, String note) {
       this.name = name;
       this.numberOfEmp = numberOfEmp;
       this.taxId = taxId;
       this.registrationNo = registrationNo;
       this.phone = phone;
       this.mail = mail;
       this.fax = fax;
       this.address = address;
       this.city = city;
       this.zipcode = zipcode;
       this.country = country;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getNumberOfEmp() {
        return this.numberOfEmp;
    }
    
    public void setNumberOfEmp(Integer numberOfEmp) {
        this.numberOfEmp = numberOfEmp;
    }
    public String getTaxId() {
        return this.taxId;
    }
    
    public void setTaxId(String taxId) {
        this.taxId = taxId;
    }
    public String getRegistrationNo() {
        return this.registrationNo;
    }
    
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


