package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IntervieweeDetails generated by hbm2java
 */
public class IntervieweeDetails  implements java.io.Serializable {


     private Integer idIntervieweeDetails;
     private EvaluationDocument evaluationDocument;
     private Rrf rrf;
     private String name;
     private String mobileNumber;
     private Integer status;
     private Date shortlistDate;
     private Date jobOfferedDate;
     private Date reportingDate;
     private String emailDetail;
     private Set<Interview> interviews = new HashSet<Interview>(0);
     private Set<CandidatesBacklog> candidatesBacklogs = new HashSet<CandidatesBacklog>(0);

    public IntervieweeDetails() {
    }

	
    public IntervieweeDetails(EvaluationDocument evaluationDocument, Rrf rrf, String name, String mobileNumber) {
        this.evaluationDocument = evaluationDocument;
        this.rrf = rrf;
        this.name = name;
        this.mobileNumber = mobileNumber;
    }
    public IntervieweeDetails(EvaluationDocument evaluationDocument, Rrf rrf, String name, String mobileNumber, Integer status, Date shortlistDate, Date jobOfferedDate, Date reportingDate, String emailDetail, Set<Interview> interviews, Set<CandidatesBacklog> candidatesBacklogs) {
       this.evaluationDocument = evaluationDocument;
       this.rrf = rrf;
       this.name = name;
       this.mobileNumber = mobileNumber;
       this.status = status;
       this.shortlistDate = shortlistDate;
       this.jobOfferedDate = jobOfferedDate;
       this.reportingDate = reportingDate;
       this.emailDetail = emailDetail;
       this.interviews = interviews;
       this.candidatesBacklogs = candidatesBacklogs;
    }
   
    public Integer getIdIntervieweeDetails() {
        return this.idIntervieweeDetails;
    }
    
    public void setIdIntervieweeDetails(Integer idIntervieweeDetails) {
        this.idIntervieweeDetails = idIntervieweeDetails;
    }
    public EvaluationDocument getEvaluationDocument() {
        return this.evaluationDocument;
    }
    
    public void setEvaluationDocument(EvaluationDocument evaluationDocument) {
        this.evaluationDocument = evaluationDocument;
    }
    public Rrf getRrf() {
        return this.rrf;
    }
    
    public void setRrf(Rrf rrf) {
        this.rrf = rrf;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getShortlistDate() {
        return this.shortlistDate;
    }
    
    public void setShortlistDate(Date shortlistDate) {
        this.shortlistDate = shortlistDate;
    }
    public Date getJobOfferedDate() {
        return this.jobOfferedDate;
    }
    
    public void setJobOfferedDate(Date jobOfferedDate) {
        this.jobOfferedDate = jobOfferedDate;
    }
    public Date getReportingDate() {
        return this.reportingDate;
    }
    
    public void setReportingDate(Date reportingDate) {
        this.reportingDate = reportingDate;
    }
    public String getEmailDetail() {
        return this.emailDetail;
    }
    
    public void setEmailDetail(String emailDetail) {
        this.emailDetail = emailDetail;
    }
    public Set<Interview> getInterviews() {
        return this.interviews;
    }
    
    public void setInterviews(Set<Interview> interviews) {
        this.interviews = interviews;
    }
    public Set<CandidatesBacklog> getCandidatesBacklogs() {
        return this.candidatesBacklogs;
    }
    
    public void setCandidatesBacklogs(Set<CandidatesBacklog> candidatesBacklogs) {
        this.candidatesBacklogs = candidatesBacklogs;
    }




}


