package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Interview generated by hbm2java
 */
public class Interview  implements java.io.Serializable {


     private Integer id;
     private IntervieweeDetails intervieweeDetails;
     private String interName;
     private Integer rating;
     private Date dateOfInterview;
     private Date timeOfInterview;

    public Interview() {
    }

	
    public Interview(IntervieweeDetails intervieweeDetails, String interName, Date dateOfInterview, Date timeOfInterview) {
        this.intervieweeDetails = intervieweeDetails;
        this.interName = interName;
        this.dateOfInterview = dateOfInterview;
        this.timeOfInterview = timeOfInterview;
    }
    public Interview(IntervieweeDetails intervieweeDetails, String interName, Integer rating, Date dateOfInterview, Date timeOfInterview) {
       this.intervieweeDetails = intervieweeDetails;
       this.interName = interName;
       this.rating = rating;
       this.dateOfInterview = dateOfInterview;
       this.timeOfInterview = timeOfInterview;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public IntervieweeDetails getIntervieweeDetails() {
        return this.intervieweeDetails;
    }
    
    public void setIntervieweeDetails(IntervieweeDetails intervieweeDetails) {
        this.intervieweeDetails = intervieweeDetails;
    }
    public String getInterName() {
        return this.interName;
    }
    
    public void setInterName(String interName) {
        this.interName = interName;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Date getDateOfInterview() {
        return this.dateOfInterview;
    }
    
    public void setDateOfInterview(Date dateOfInterview) {
        this.dateOfInterview = dateOfInterview;
    }
    public Date getTimeOfInterview() {
        return this.timeOfInterview;
    }
    
    public void setTimeOfInterview(Date timeOfInterview) {
        this.timeOfInterview = timeOfInterview;
    }




}


