package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JobGrade generated by hbm2java
 */
public class JobGrade  implements java.io.Serializable {


     private Integer idJb;
     private String jobGradeData;
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);

    public JobGrade() {
    }

	
    public JobGrade(String jobGradeData) {
        this.jobGradeData = jobGradeData;
    }
    public JobGrade(String jobGradeData, Set<Rrf> rrfs) {
       this.jobGradeData = jobGradeData;
       this.rrfs = rrfs;
    }
   
    public Integer getIdJb() {
        return this.idJb;
    }
    
    public void setIdJb(Integer idJb) {
        this.idJb = idJb;
    }
    public String getJobGradeData() {
        return this.jobGradeData;
    }
    
    public void setJobGradeData(String jobGradeData) {
        this.jobGradeData = jobGradeData;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }




}


