package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JobTitle generated by hbm2java
 */
public class JobTitle  implements java.io.Serializable {


     private Integer id;
     private String jobTitle;
     private String description;
     private String note;
     private boolean isDeleted;
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);

    public JobTitle() {
    }

	
    public JobTitle(String jobTitle, boolean isDeleted) {
        this.jobTitle = jobTitle;
        this.isDeleted = isDeleted;
    }
    public JobTitle(String jobTitle, String description, String note, boolean isDeleted, Set<Rrf> rrfs) {
       this.jobTitle = jobTitle;
       this.description = description;
       this.note = note;
       this.isDeleted = isDeleted;
       this.rrfs = rrfs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }




}


