package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * NarrowvationArticle generated by hbm2java
 */
public class NarrowvationArticle  implements java.io.Serializable {


     private int id;
     private Article article;
     private ExistingEmpList existingEmpList;
     private String narrowvationArticle;

    public NarrowvationArticle() {
    }

    public NarrowvationArticle(int id, Article article, ExistingEmpList existingEmpList, String narrowvationArticle) {
       this.id = id;
       this.article = article;
       this.existingEmpList = existingEmpList;
       this.narrowvationArticle = narrowvationArticle;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public ExistingEmpList getExistingEmpList() {
        return this.existingEmpList;
    }
    
    public void setExistingEmpList(ExistingEmpList existingEmpList) {
        this.existingEmpList = existingEmpList;
    }
    public String getNarrowvationArticle() {
        return this.narrowvationArticle;
    }
    
    public void setNarrowvationArticle(String narrowvationArticle) {
        this.narrowvationArticle = narrowvationArticle;
    }




}


