package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ReasonForReqruitment generated by hbm2java
 */
public class ReasonForReqruitment  implements java.io.Serializable {


     private Integer idReasonForReqruitment;
     private String reason;
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);

    public ReasonForReqruitment() {
    }

	
    public ReasonForReqruitment(String reason) {
        this.reason = reason;
    }
    public ReasonForReqruitment(String reason, Set<Rrf> rrfs) {
       this.reason = reason;
       this.rrfs = rrfs;
    }
   
    public Integer getIdReasonForReqruitment() {
        return this.idReasonForReqruitment;
    }
    
    public void setIdReasonForReqruitment(Integer idReasonForReqruitment) {
        this.idReasonForReqruitment = idReasonForReqruitment;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }




}


