package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * ReportingPersonRrf generated by hbm2java
 */
public class ReportingPersonRrf  implements java.io.Serializable {


     private Integer idReportingPersonRrf;
     private ExistingEmpList existingEmpList;
     private Rrf rrf;

    public ReportingPersonRrf() {
    }

    public ReportingPersonRrf(ExistingEmpList existingEmpList, Rrf rrf) {
       this.existingEmpList = existingEmpList;
       this.rrf = rrf;
    }
   
    public Integer getIdReportingPersonRrf() {
        return this.idReportingPersonRrf;
    }
    
    public void setIdReportingPersonRrf(Integer idReportingPersonRrf) {
        this.idReportingPersonRrf = idReportingPersonRrf;
    }
    public ExistingEmpList getExistingEmpList() {
        return this.existingEmpList;
    }
    
    public void setExistingEmpList(ExistingEmpList existingEmpList) {
        this.existingEmpList = existingEmpList;
    }
    public Rrf getRrf() {
        return this.rrf;
    }
    
    public void setRrf(Rrf rrf) {
        this.rrf = rrf;
    }




}


