package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RrfBacklog generated by hbm2java
 */
public class RrfBacklog  implements java.io.Serializable {


     private Integer idRrfBacklog;
     private Rrf rrf;
     private User user;
     private String details;
     private Date dateTime;

    public RrfBacklog() {
    }

	
    public RrfBacklog(Rrf rrf, User user, Date dateTime) {
        this.rrf = rrf;
        this.user = user;
        this.dateTime = dateTime;
    }
    public RrfBacklog(Rrf rrf, User user, String details, Date dateTime) {
       this.rrf = rrf;
       this.user = user;
       this.details = details;
       this.dateTime = dateTime;
    }
   
    public Integer getIdRrfBacklog() {
        return this.idRrfBacklog;
    }
    
    public void setIdRrfBacklog(Integer idRrfBacklog) {
        this.idRrfBacklog = idRrfBacklog;
    }
    public Rrf getRrf() {
        return this.rrf;
    }
    
    public void setRrf(Rrf rrf) {
        this.rrf = rrf;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


