package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1



/**
 * SalaryGrade generated by hbm2java
 */
public class SalaryGrade  implements java.io.Serializable {


     private Integer idSalaryGrade;
     private String salaryGradeDetails;

    public SalaryGrade() {
    }

    public SalaryGrade(String salaryGradeDetails) {
       this.salaryGradeDetails = salaryGradeDetails;
    }
   
    public Integer getIdSalaryGrade() {
        return this.idSalaryGrade;
    }
    
    public void setIdSalaryGrade(Integer idSalaryGrade) {
        this.idSalaryGrade = idSalaryGrade;
    }
    public String getSalaryGradeDetails() {
        return this.salaryGradeDetails;
    }
    
    public void setSalaryGradeDetails(String salaryGradeDetails) {
        this.salaryGradeDetails = salaryGradeDetails;
    }




}


