package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TerminatedEmployees generated by hbm2java
 */
public class TerminatedEmployees  implements java.io.Serializable {


     private Integer id;
     private CustomStatus customStatus;
     private ExistingEmpList existingEmpList;
     private String reason;
     private Date dateOfTermination;
     private Date submitDate;
     private Date requestDateOfTermination;

    public TerminatedEmployees() {
    }

	
    public TerminatedEmployees(CustomStatus customStatus, ExistingEmpList existingEmpList, Date dateOfTermination) {
        this.customStatus = customStatus;
        this.existingEmpList = existingEmpList;
        this.dateOfTermination = dateOfTermination;
    }
    public TerminatedEmployees(CustomStatus customStatus, ExistingEmpList existingEmpList, String reason, Date dateOfTermination, Date submitDate, Date requestDateOfTermination) {
       this.customStatus = customStatus;
       this.existingEmpList = existingEmpList;
       this.reason = reason;
       this.dateOfTermination = dateOfTermination;
       this.submitDate = submitDate;
       this.requestDateOfTermination = requestDateOfTermination;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CustomStatus getCustomStatus() {
        return this.customStatus;
    }
    
    public void setCustomStatus(CustomStatus customStatus) {
        this.customStatus = customStatus;
    }
    public ExistingEmpList getExistingEmpList() {
        return this.existingEmpList;
    }
    
    public void setExistingEmpList(ExistingEmpList existingEmpList) {
        this.existingEmpList = existingEmpList;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getDateOfTermination() {
        return this.dateOfTermination;
    }
    
    public void setDateOfTermination(Date dateOfTermination) {
        this.dateOfTermination = dateOfTermination;
    }
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }
    public Date getRequestDateOfTermination() {
        return this.requestDateOfTermination;
    }
    
    public void setRequestDateOfTermination(Date requestDateOfTermination) {
        this.requestDateOfTermination = requestDateOfTermination;
    }




}


