package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private AccessLevel accessLevel;
     private UserRole userRole;
     private String empNo;
     private String userName;
     private String password;
     private Date dateEntered;
     private Date dateModified;
     private Integer modifiedUserId;
     private Integer createdBy;
     private boolean states;
     private boolean deleted;
     private Integer reportingPerson;
     private Set<Rrf> rrfs = new HashSet<Rrf>(0);
     private Set<History> histories = new HashSet<History>(0);
     private Set<ArticleBacklog> articleBacklogs = new HashSet<ArticleBacklog>(0);
     private Set<RrfBacklog> rrfBacklogs = new HashSet<RrfBacklog>(0);
     private Set<UserPreference> userPreferences = new HashSet<UserPreference>(0);
     private Set<CandidatesBacklog> candidatesBacklogs = new HashSet<CandidatesBacklog>(0);
     private Set<EmployeeBacklog> employeeBacklogs = new HashSet<EmployeeBacklog>(0);

    public User() {
    }

	
    public User(AccessLevel accessLevel, UserRole userRole, String userName, String password, boolean states, boolean deleted) {
        this.accessLevel = accessLevel;
        this.userRole = userRole;
        this.userName = userName;
        this.password = password;
        this.states = states;
        this.deleted = deleted;
    }
    public User(AccessLevel accessLevel, UserRole userRole, String empNo, String userName, String password, Date dateEntered, Date dateModified, Integer modifiedUserId, Integer createdBy, boolean states, boolean deleted, Integer reportingPerson, Set<Rrf> rrfs, Set<History> histories, Set<ArticleBacklog> articleBacklogs, Set<RrfBacklog> rrfBacklogs, Set<UserPreference> userPreferences, Set<CandidatesBacklog> candidatesBacklogs, Set<EmployeeBacklog> employeeBacklogs) {
       this.accessLevel = accessLevel;
       this.userRole = userRole;
       this.empNo = empNo;
       this.userName = userName;
       this.password = password;
       this.dateEntered = dateEntered;
       this.dateModified = dateModified;
       this.modifiedUserId = modifiedUserId;
       this.createdBy = createdBy;
       this.states = states;
       this.deleted = deleted;
       this.reportingPerson = reportingPerson;
       this.rrfs = rrfs;
       this.histories = histories;
       this.articleBacklogs = articleBacklogs;
       this.rrfBacklogs = rrfBacklogs;
       this.userPreferences = userPreferences;
       this.candidatesBacklogs = candidatesBacklogs;
       this.employeeBacklogs = employeeBacklogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AccessLevel getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(AccessLevel accessLevel) {
        this.accessLevel = accessLevel;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public String getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateEntered() {
        return this.dateEntered;
    }
    
    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Integer getModifiedUserId() {
        return this.modifiedUserId;
    }
    
    public void setModifiedUserId(Integer modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public boolean isStates() {
        return this.states;
    }
    
    public void setStates(boolean states) {
        this.states = states;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public Integer getReportingPerson() {
        return this.reportingPerson;
    }
    
    public void setReportingPerson(Integer reportingPerson) {
        this.reportingPerson = reportingPerson;
    }
    public Set<Rrf> getRrfs() {
        return this.rrfs;
    }
    
    public void setRrfs(Set<Rrf> rrfs) {
        this.rrfs = rrfs;
    }
    public Set<History> getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }
    public Set<ArticleBacklog> getArticleBacklogs() {
        return this.articleBacklogs;
    }
    
    public void setArticleBacklogs(Set<ArticleBacklog> articleBacklogs) {
        this.articleBacklogs = articleBacklogs;
    }
    public Set<RrfBacklog> getRrfBacklogs() {
        return this.rrfBacklogs;
    }
    
    public void setRrfBacklogs(Set<RrfBacklog> rrfBacklogs) {
        this.rrfBacklogs = rrfBacklogs;
    }
    public Set<UserPreference> getUserPreferences() {
        return this.userPreferences;
    }
    
    public void setUserPreferences(Set<UserPreference> userPreferences) {
        this.userPreferences = userPreferences;
    }
    public Set<CandidatesBacklog> getCandidatesBacklogs() {
        return this.candidatesBacklogs;
    }
    
    public void setCandidatesBacklogs(Set<CandidatesBacklog> candidatesBacklogs) {
        this.candidatesBacklogs = candidatesBacklogs;
    }
    public Set<EmployeeBacklog> getEmployeeBacklogs() {
        return this.employeeBacklogs;
    }
    
    public void setEmployeeBacklogs(Set<EmployeeBacklog> employeeBacklogs) {
        this.employeeBacklogs = employeeBacklogs;
    }




}


