package map_hr;
// Generated Dec 2, 2016 11:52:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer idUserRole;
     private String name;
     private String displayName;
     private boolean isAssignable;
     private Set<User> users = new HashSet<User>(0);

    public UserRole() {
    }

	
    public UserRole(String name, String displayName, boolean isAssignable) {
        this.name = name;
        this.displayName = displayName;
        this.isAssignable = isAssignable;
    }
    public UserRole(String name, String displayName, boolean isAssignable, Set<User> users) {
       this.name = name;
       this.displayName = displayName;
       this.isAssignable = isAssignable;
       this.users = users;
    }
   
    public Integer getIdUserRole() {
        return this.idUserRole;
    }
    
    public void setIdUserRole(Integer idUserRole) {
        this.idUserRole = idUserRole;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public boolean isIsAssignable() {
        return this.isAssignable;
    }
    
    public void setIsAssignable(boolean isAssignable) {
        this.isAssignable = isAssignable;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


