package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AccountCode generated by hbm2java
 */
public class AccountCode  implements java.io.Serializable {


     private Integer idAccountCode;
     private Department department;
     private String name;
     private String codeName;
     private Date dateGiven;
     private Date terminate;
     private String status;

    public AccountCode() {
    }

    public AccountCode(Department department, String name, String codeName, Date dateGiven, Date terminate, String status) {
       this.department = department;
       this.name = name;
       this.codeName = codeName;
       this.dateGiven = dateGiven;
       this.terminate = terminate;
       this.status = status;
    }
   
    public Integer getIdAccountCode() {
        return this.idAccountCode;
    }
    
    public void setIdAccountCode(Integer idAccountCode) {
        this.idAccountCode = idAccountCode;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCodeName() {
        return this.codeName;
    }
    
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }
    public Date getDateGiven() {
        return this.dateGiven;
    }
    
    public void setDateGiven(Date dateGiven) {
        this.dateGiven = dateGiven;
    }
    public Date getTerminate() {
        return this.terminate;
    }
    
    public void setTerminate(Date terminate) {
        this.terminate = terminate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


