package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer idbranch;
     private HeadBranch headBranch;
     private String branchName;
     private String tel;
     private String speedDial;
     private String fax;
     private String didNo;
     private Set<HeadbranchHasBranch> headbranchHasBranches = new HashSet<HeadbranchHasBranch>(0);

    public Branch() {
    }

    public Branch(HeadBranch headBranch, String branchName, String tel, String speedDial, String fax, String didNo, Set<HeadbranchHasBranch> headbranchHasBranches) {
       this.headBranch = headBranch;
       this.branchName = branchName;
       this.tel = tel;
       this.speedDial = speedDial;
       this.fax = fax;
       this.didNo = didNo;
       this.headbranchHasBranches = headbranchHasBranches;
    }
    
    public Branch(String branchName, String tel, String speedDial, String fax, String didNo) {
      
       this.branchName = branchName;
       this.tel = tel;
       this.speedDial = speedDial;
       this.fax = fax;
       this.didNo = didNo;
       
    }
    
   
    public Integer getIdbranch() {
        return this.idbranch;
    }
    
    public void setIdbranch(Integer idbranch) {
        this.idbranch = idbranch;
    }
    public HeadBranch getHeadBranch() {
        return this.headBranch;
    }
    
    public void setHeadBranch(HeadBranch headBranch) {
        this.headBranch = headBranch;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getSpeedDial() {
        return this.speedDial;
    }
    
    public void setSpeedDial(String speedDial) {
        this.speedDial = speedDial;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getDidNo() {
        return this.didNo;
    }
    
    public void setDidNo(String didNo) {
        this.didNo = didNo;
    }
    public Set<HeadbranchHasBranch> getHeadbranchHasBranches() {
        return this.headbranchHasBranches;
    }
    
    public void setHeadbranchHasBranches(Set<HeadbranchHasBranch> headbranchHasBranches) {
        this.headbranchHasBranches = headbranchHasBranches;
    }




}


