package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer iddepartment;
     private HeadDepartment headDepartment;
     private String departmentName;
     private Integer departmentOrder;
     private Set<Assignee> assignees = new HashSet<Assignee>(0);
     private Set<AccountCode> accountCodes = new HashSet<AccountCode>(0);
     private Set<HeaddeptHasDept> headdeptHasDepts = new HashSet<HeaddeptHasDept>(0);

    public Department() {
    }

    public Department(HeadDepartment headDepartment, String departmentName, Integer departmentOrder, Set<Assignee> assignees, Set<AccountCode> accountCodes, Set<HeaddeptHasDept> headdeptHasDepts) {
       this.headDepartment = headDepartment;
       this.departmentName = departmentName;
       this.departmentOrder = departmentOrder;
       this.assignees = assignees;
       this.accountCodes = accountCodes;
       this.headdeptHasDepts = headdeptHasDepts;
    }
   
    public Integer getIddepartment() {
        return this.iddepartment;
    }
    
    public void setIddepartment(Integer iddepartment) {
        this.iddepartment = iddepartment;
    }
    public HeadDepartment getHeadDepartment() {
        return this.headDepartment;
    }
    
    public void setHeadDepartment(HeadDepartment headDepartment) {
        this.headDepartment = headDepartment;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Integer getDepartmentOrder() {
        return this.departmentOrder;
    }
    
    public void setDepartmentOrder(Integer departmentOrder) {
        this.departmentOrder = departmentOrder;
    }
    public Set<Assignee> getAssignees() {
        return this.assignees;
    }
    
    public void setAssignees(Set<Assignee> assignees) {
        this.assignees = assignees;
    }
    public Set<AccountCode> getAccountCodes() {
        return this.accountCodes;
    }
    
    public void setAccountCodes(Set<AccountCode> accountCodes) {
        this.accountCodes = accountCodes;
    }
    public Set<HeaddeptHasDept> getHeaddeptHasDepts() {
        return this.headdeptHasDepts;
    }
    
    public void setHeaddeptHasDepts(Set<HeaddeptHasDept> headdeptHasDepts) {
        this.headdeptHasDepts = headdeptHasDepts;
    }




}


