package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Extension generated by hbm2java
 */
public class Extension  implements java.io.Serializable {


     private Integer idExtension;
     private String extensionNo;
     private String virtualExt;
     private String forwordExt;
     private String forwdExt1;
     private String forwdExt2;
     private String forwdExt3;
     private String forwdExt4;
     private Set<RegisterHasExt> registerHasExts = new HashSet<RegisterHasExt>(0);
     private Set<Assignee> assignees = new HashSet<Assignee>(0);
     private Set<UserHasExt> userHasExts = new HashSet<UserHasExt>(0);

    public Extension() {
    }

    public Extension(String extensionNo, String virtualExt, String forwordExt, String forwdExt1, String forwdExt2, String forwdExt3, String forwdExt4, Set<RegisterHasExt> registerHasExts, Set<Assignee> assignees, Set<UserHasExt> userHasExts) {
       this.extensionNo = extensionNo;
       this.virtualExt = virtualExt;
       this.forwordExt = forwordExt;
       this.forwdExt1 = forwdExt1;
       this.forwdExt2 = forwdExt2;
       this.forwdExt3 = forwdExt3;
       this.forwdExt4 = forwdExt4;
       this.registerHasExts = registerHasExts;
       this.assignees = assignees;
       this.userHasExts = userHasExts;
    }
   
    public Integer getIdExtension() {
        return this.idExtension;
    }
    
    public void setIdExtension(Integer idExtension) {
        this.idExtension = idExtension;
    }
    public String getExtensionNo() {
        return this.extensionNo;
    }
    
    public void setExtensionNo(String extensionNo) {
        this.extensionNo = extensionNo;
    }
    public String getVirtualExt() {
        return this.virtualExt;
    }
    
    public void setVirtualExt(String virtualExt) {
        this.virtualExt = virtualExt;
    }
    public String getForwordExt() {
        return this.forwordExt;
    }
    
    public void setForwordExt(String forwordExt) {
        this.forwordExt = forwordExt;
    }
    public String getForwdExt1() {
        return this.forwdExt1;
    }
    
    public void setForwdExt1(String forwdExt1) {
        this.forwdExt1 = forwdExt1;
    }
    public String getForwdExt2() {
        return this.forwdExt2;
    }
    
    public void setForwdExt2(String forwdExt2) {
        this.forwdExt2 = forwdExt2;
    }
    public String getForwdExt3() {
        return this.forwdExt3;
    }
    
    public void setForwdExt3(String forwdExt3) {
        this.forwdExt3 = forwdExt3;
    }
    public String getForwdExt4() {
        return this.forwdExt4;
    }
    
    public void setForwdExt4(String forwdExt4) {
        this.forwdExt4 = forwdExt4;
    }
    public Set<RegisterHasExt> getRegisterHasExts() {
        return this.registerHasExts;
    }
    
    public void setRegisterHasExts(Set<RegisterHasExt> registerHasExts) {
        this.registerHasExts = registerHasExts;
    }
    public Set<Assignee> getAssignees() {
        return this.assignees;
    }
    
    public void setAssignees(Set<Assignee> assignees) {
        this.assignees = assignees;
    }
    public Set<UserHasExt> getUserHasExts() {
        return this.userHasExts;
    }
    
    public void setUserHasExts(Set<UserHasExt> userHasExts) {
        this.userHasExts = userHasExts;
    }




}


