package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HeadBranch generated by hbm2java
 */
public class HeadBranch  implements java.io.Serializable {


     private int idheadBranch;
     private String headBranchName;
     private Set<Branch> branches = new HashSet<Branch>(0);
     private Set<HeadbranchHasBranch> headbranchHasBranches = new HashSet<HeadbranchHasBranch>(0);

    public HeadBranch() {
    }

	
    public HeadBranch(int idheadBranch) {
        this.idheadBranch = idheadBranch;
    }
    public HeadBranch(int idheadBranch, String headBranchName, Set<Branch> branches, Set<HeadbranchHasBranch> headbranchHasBranches) {
       this.idheadBranch = idheadBranch;
       this.headBranchName = headBranchName;
       this.branches = branches;
       this.headbranchHasBranches = headbranchHasBranches;
    }
   
    public int getIdheadBranch() {
        return this.idheadBranch;
    }
    
    public void setIdheadBranch(int idheadBranch) {
        this.idheadBranch = idheadBranch;
    }
    public String getHeadBranchName() {
        return this.headBranchName;
    }
    
    public void setHeadBranchName(String headBranchName) {
        this.headBranchName = headBranchName;
    }
    public Set<Branch> getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set<Branch> branches) {
        this.branches = branches;
    }
    public Set<HeadbranchHasBranch> getHeadbranchHasBranches() {
        return this.headbranchHasBranches;
    }
    
    public void setHeadbranchHasBranches(Set<HeadbranchHasBranch> headbranchHasBranches) {
        this.headbranchHasBranches = headbranchHasBranches;
    }




}


