package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1



/**
 * HeadbranchHasBranch generated by hbm2java
 */
public class HeadbranchHasBranch  implements java.io.Serializable {


     private Integer idheadbranchHasBranch;
     private Branch branch;
     private HeadBranch headBranch;

    public HeadbranchHasBranch() {
    }

    public HeadbranchHasBranch(Branch branch, HeadBranch headBranch) {
       this.branch = branch;
       this.headBranch = headBranch;
    }
   
    public Integer getIdheadbranchHasBranch() {
        return this.idheadbranchHasBranch;
    }
    
    public void setIdheadbranchHasBranch(Integer idheadbranchHasBranch) {
        this.idheadbranchHasBranch = idheadbranchHasBranch;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public HeadBranch getHeadBranch() {
        return this.headBranch;
    }
    
    public void setHeadBranch(HeadBranch headBranch) {
        this.headBranch = headBranch;
    }




}


