package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HeadDepartment generated by hbm2java
 */
public class HeadDepartment  implements java.io.Serializable {


     private int idheadDepartment;
     private String headDepartName;
     private Integer headDepartmentOrder;
     private Set<Department> departments = new HashSet<Department>(0);
     private Set<HeaddeptHasDept> headdeptHasDepts = new HashSet<HeaddeptHasDept>(0);

    public HeadDepartment() {
    }

	
    public HeadDepartment(int idheadDepartment) {
        this.idheadDepartment = idheadDepartment;
    }
    public HeadDepartment(int idheadDepartment, String headDepartName, Integer headDepartmentOrder, Set<Department> departments, Set<HeaddeptHasDept> headdeptHasDepts) {
       this.idheadDepartment = idheadDepartment;
       this.headDepartName = headDepartName;
       this.headDepartmentOrder = headDepartmentOrder;
       this.departments = departments;
       this.headdeptHasDepts = headdeptHasDepts;
    }
   
    public int getIdheadDepartment() {
        return this.idheadDepartment;
    }
    
    public void setIdheadDepartment(int idheadDepartment) {
        this.idheadDepartment = idheadDepartment;
    }
    public String getHeadDepartName() {
        return this.headDepartName;
    }
    
    public void setHeadDepartName(String headDepartName) {
        this.headDepartName = headDepartName;
    }
    public Integer getHeadDepartmentOrder() {
        return this.headDepartmentOrder;
    }
    
    public void setHeadDepartmentOrder(Integer headDepartmentOrder) {
        this.headDepartmentOrder = headDepartmentOrder;
    }
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }
    public Set<HeaddeptHasDept> getHeaddeptHasDepts() {
        return this.headdeptHasDepts;
    }
    
    public void setHeaddeptHasDepts(Set<HeaddeptHasDept> headdeptHasDepts) {
        this.headdeptHasDepts = headdeptHasDepts;
    }




}


