package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer idregister;
     private String username;
     private String email;
     private String fullname;
     private String requestedTime;
     private String clientIp;
     private String status;
     private String approvedBy;
     private Set<RegisterHasExt> registerHasExts = new HashSet<RegisterHasExt>(0);

    public Register() {
    }

    public Register(String username, String email, String fullname, String requestedTime, String clientIp, String status, String approvedBy, Set<RegisterHasExt> registerHasExts) {
       this.username = username;
       this.email = email;
       this.fullname = fullname;
       this.requestedTime = requestedTime;
       this.clientIp = clientIp;
       this.status = status;
       this.approvedBy = approvedBy;
       this.registerHasExts = registerHasExts;
    }
   
    public Integer getIdregister() {
        return this.idregister;
    }
    
    public void setIdregister(Integer idregister) {
        this.idregister = idregister;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getRequestedTime() {
        return this.requestedTime;
    }
    
    public void setRequestedTime(String requestedTime) {
        this.requestedTime = requestedTime;
    }
    public String getClientIp() {
        return this.clientIp;
    }
    
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }
    public Set<RegisterHasExt> getRegisterHasExts() {
        return this.registerHasExts;
    }
    
    public void setRegisterHasExts(Set<RegisterHasExt> registerHasExts) {
        this.registerHasExts = registerHasExts;
    }




}


