package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1



/**
 * RegisterHasExt generated by hbm2java
 */
public class RegisterHasExt  implements java.io.Serializable {


     private Integer idregisterHasExtension;
     private Extension extension;
     private Register register;

    public RegisterHasExt() {
    }

    public RegisterHasExt(Extension extension, Register register) {
       this.extension = extension;
       this.register = register;
    }
   
    public Integer getIdregisterHasExtension() {
        return this.idregisterHasExtension;
    }
    
    public void setIdregisterHasExtension(Integer idregisterHasExtension) {
        this.idregisterHasExtension = idregisterHasExtension;
    }
    public Extension getExtension() {
        return this.extension;
    }
    
    public void setExtension(Extension extension) {
        this.extension = extension;
    }
    public Register getRegister() {
        return this.register;
    }
    
    public void setRegister(Register register) {
        this.register = register;
    }




}


