package map;
// Generated Dec 2, 2016 11:41:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String username;
     private String fullName;
     private Date createTime;
     private String type;
     private String status;
     private Set<UserHasExt> userHasExts = new HashSet<UserHasExt>(0);

    public User() {
    }

    public User(String username, String fullName, Date createTime, String type, String status, Set<UserHasExt> userHasExts) {
       this.username = username;
       this.fullName = fullName;
       this.createTime = createTime;
       this.type = type;
       this.status = status;
       this.userHasExts = userHasExts;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserHasExt> getUserHasExts() {
        return this.userHasExts;
    }
    
    public void setUserHasExts(Set<UserHasExt> userHasExts) {
        this.userHasExts = userHasExts;
    }




}


